[workspace]
# members = ["app", "db", "keybinding", "memory", "redborm", "tserv", "widgets"]
# Disable some borked crates as an expedient
members = [
  "handler",
  "keybinding",
  "lid",
  "memory",
  "memory/redb",
  "redborm",
  "timestamp",
  "tserv",
  "widgets",
]

resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
exocortex-handler = { path = "handler" }
exocortex-lid = { path = "lid" }
exocortex-memory = { path = "memory" }
exocortex-redborm = { path = "redborm" }
exocortex-timestamp = { path = "timestamp" }
exocortex-tserv = { path = "tserv" }

derive-new = "0.7.0"
derive_builder = "0.20.2"
derive_more = "2.1.1"
disqualified = "1.0.0"
egui = "0.33"
extension-traits = "2.0.1"
jiff = "0.2.23"
log = "0.4.29"
moveslot = "0.1.0"
redb = "3.1.1"
redb-derive = "0.1.0"
thiserror = "2.0.17"
