[package]
edition.workspace = true
name = "exocortex-redborm"
version = "0.1.0"

[dependencies]
derive-new.workspace = true
derive_more = { workspace = true, features = ["from", "into"] }
exocortex-lid = { workspace = true, features = ["redb"] }
extension-traits.workspace = true
redb.workspace = true
redb-derive.workspace = true
thiserror.workspace = true
