#!/bin/bash
set -efuo pipefail

function main
{
  cmd="${1:-check-everything}"

  eval "$cmd"
}

function check-everything
{
  [ -n "${IN_NIX_SHELL:-}" ] || fail 'must be in `nix develop` shell'
  unstaged_is_dirty && fail 'refusing to proceed with unstaged changes'

  auto-fmt-tomls
  v cargo check
  v git add Cargo.lock

  shear-happy
  check-each-crate
  gauntlet
}

function shear-happy
{
  if [ "$(cargo shear --frozen --format=json | jq '.summary | all(.[]; . == 0)')" = 'true' ]
  then
    echo 'cargo shear happy'
  else
    v cargo shear --frozen
    return -1
  fi
}

function check-each-crate
{
  # Check each crate individually to catch "ambient workspace" misconfigurations like feature flags:
  for cratedir in $(parse-member-crate-dirs)
  do
    v cargo check --manifest-path "$cratedir/Cargo.toml"
  done
}

function fail
{
  echo "$*"
  exit 1
}

function unstaged_is_dirty
{
  git status --porcelain | rg '^.[^ ]'
}

function auto-fmt-tomls
{
  v taplo format
  git diff
  v git add $(fd -g '*.toml')
}

function gauntlet
{
  v cargo build "$@"
  v cargo doc "$@"
  v cargo clippy "$@"
  v cargo test "$@"
}

function parse-member-crate-dirs
{
  rg -U '(?s)^members = \[[^\]]+\]' Cargo.toml | sd '^members = |\[|\]|[",]' ''
}

function v
{
  echo "=== $*"
  eval "$@"
}

main "$@"
