[package]
edition.workspace = true
name = "exocortex-memory-ram"
version = "0.1.0"

[dependencies]
derive_more = { workspace = true, features = ["from", "try_into"] }
exocortex-handler.workspace = true
exocortex-lid.workspace = true
exocortex-memory.workspace = true
exocortex-thop.workspace = true
exocortex-timestamp.workspace = true
thiserror.workspace = true
